apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    #do not push to dockerhub whenever we build an image
    #which is the default behav
    push: false

  artifacts:
    #image to build
    - image: falco9017/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          #take this files and put it in the dest
          - src: 'src/**/*.ts'
            #same path inside the container
            dest: .
    - image: falco9017/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          #take this files and put it in the dest
          - src: '**/*.js'
            #same path inside the container
            dest: .
